### ISSUE TITLE
Error running Jest tests

### ISSUE THREAD

**Issue by bernhardwaidacher** [protomodule/probe#1]
When running jest tests, jest automatically sets `NODE_ENV` to `test` which results in an error:

` ``   Fatal misconfiguration in environment variables
    
    
    ╭───────────────────────   Invalid environment variables   ────────────────────────╮
    │                                                                                  │
    │   NODE_ENV: Value "test" not in choices [local,development,staging,production]   │
    │                                                                                  │
    ╰──────────────────────────────────────────────────────────────────────────────────╯
```

Please add `test` as a valid NODE_ENV

**Comment by lukaskorl** [comment]
We have two possibilities:
1. Use a custom environment configuration https://github.com/protomodule/probe/blob/main/docs/config.md#custom-runtime-environments.
2. Add `test` by default to the list of environments.

I tend to go with option 2. Any opinions?

**Comment by bernhardwaidacher** [comment]
Since jest is a widely used framework, I would also suggest to add `test` to the list of environments

**Comment by lukaskorl** [comment]
@bernhardwaidacher `test` is included from version v0.2.0 onwards by default (https://github.com/protomodule/probe/releases/tag/v0.2.0)
